name: Build and Store Docker Image

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the action

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: "Set current date as env variable"
      id: version
      run: |
          echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: "Set short SHA"
      id: sha
      run: |
          echo "shortsha=$(echo ${GITHUB_SHA::7})" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      env:
        BUILD_DATE: $GITHUB_OUTPUT
        BUILD_NUMBER: ${{ github.run_number }}
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-octane:${{ steps.sha.outputs.shortsha }}
          ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-octane:${{ steps.version.outputs.builddate }}