name: Build and Store Docker Image

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the action

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Get current date
      id: current_date
      run: echo "{name}=date::$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      env:
        BUILD_DATE: ${{ $GITHUB_OUTPUT }}
        BUILD_NUMBER: ${{ github.run_number }}
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-octane:build-${{ env.BUILD_NUMBER }}
          ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-octane:${{ env.BUILD_DATE }}